### ISSUE TITLE
关于内存分配函数

### ISSUE THREAD

**Issue by LiuYinCarl** [colinsusie/colib#1]
作者您好，在 `src/coconf.h` 中使用的内存分配函数是 `malloc/free/realloc/calloc`，而不是Lua 提供的 `src/lmem.h` 中的 `luaM_realloc_`，我觉得这个设计可能会导致 Lua 不能够正确的统计到程序使用总内存量，如果使用者修改了 `luaM_realloc`，使用了自定义的内存池来监控内存，也应该会导致内存统计出现偏差。不知道您这个设计是有什么其他目的吗？

**Comment by colinsusie** [comment]
首先这个luaM_realloc_是Lua的内部实现，不是对外的API，外部模块必须使用`Reference Manual`里面提到的API，你说的应该是这个`lua_getallocf`，即我得先调用这个API取得分配函数，再调用它得到内存。

但是lua_getallocf的默认实现只是一个简单的内存分配函数，并没有提供内存用量的统计。

Lua统计的只是受它管理的对象的内存使用，以此来指导GC的回收。对于外部它其实是不关心的，而程序也不能把内存管理和Lua绑在一起。

**Comment by LiuYinCarl** [comment]
我懂您的意思了。如果按照您这个思路，可以实现一个 `hash_map` 或者实现一个 Lua 的 Table，用来存储一些需要避免 GC 的地方，比如大量的配置表之类。这样子可以在不修改 Lua 源码的前提下，减轻 Lua GC 的负担，不知道我的理解对不对？

**Comment by LiuYinCarl** [comment]
另外，Lua 是可以通过 `global_State->GCdebt` 统计内存用量的

**Comment by colinsusie** [comment]
你可以实现userdata，userdata这个对象受Lua管理，但它里面的内容不受Lua管。比如配置表实现为一个userdata，然后通过元方法给Lua访问配置的内存

**Comment by colinsusie** [comment]
global_State->GCdebt  是Lua源码内部的事，你不能去用它。

**Comment by LiuYinCarl** [comment]
清楚了，感谢👍
